In [41]:
#import modules
from osgeo import ogr, gdal, osr
import numpy as np
import os
import matplotlib.pyplot as plt

In [42]:
#Input rasters (clipped)

#Image-2018
path_NDVI_2017="../Neretva_NDVI_clip/clipped_2017.tif"

#Image-2017
path_NDVI_2018="../Neretva_NDVI_clip/clipped_2018.tif"

In [43]:
#Open raster bands
NDVI_2017 = gdal.Open(path_NDVI_2017)
NDVI_2018 = gdal.Open(path_NDVI_2018)

#Read bands as matrix arrays
NDVI_2017_data = NDVI_2017.GetRasterBand(1).ReadAsArray().astype(np.float32)
NDVI_2018_data = NDVI_2018.GetRasterBand(1).ReadAsArray().astype(np.float32)

In [44]:
print(NDVI_2017.GetProjection()[:980])
print(NDVI_2018.GetProjection()[:980])
if NDVI_2017.GetProjection()[:80]==NDVI_2018.GetProjection()[:80]: print('SRC OK')

PROJCS["WGS 84 / Pseudo-Mercator",GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4326"]],PROJECTION["Mercator_1SP"],PARAMETER["central_meridian",0],PARAMETER["scale_factor",1],PARAMETER["false_easting",0],PARAMETER["false_northing",0],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AXIS["X",EAST],AXIS["Y",NORTH],EXTENSION["PROJ4","+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs"],AUTHORITY["EPSG","3857"]]
PROJCS["WGS 84 / Pseudo-Mercator",GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4326"]],PROJECTION["Mercator_1SP"],PARAM

In [45]:
print(NDVI_2017_data.shape)
print(NDVI_2018_data.shape)
if NDVI_2017_data.shape==NDVI_2018_data.shape: print('Array Size OK')

(488, 826)
(488, 826)
Array Size OK


In [46]:
print(NDVI_2017_data)
print(NDVI_2018_data)

[[0.   0.   0.   ... 0.   0.19 0.  ]
 [0.   0.   0.   ... 0.   0.   0.  ]
 [0.06 0.   0.   ... 0.   0.   0.  ]
 ...
 [0.   0.06 0.13 ... 0.31 0.25 0.  ]
 [0.   0.   0.   ... 0.31 0.31 0.  ]
 [0.   0.   0.   ... 0.25 0.31 0.  ]]
[[0.   0.   0.   ... 0.   0.   0.  ]
 [0.06 0.   0.   ... 0.   0.   0.  ]
 [0.13 0.   0.   ... 0.   0.   0.  ]
 ...
 [0.   0.   0.   ... 0.25 0.31 0.  ]
 [0.   0.   0.   ... 0.25 0.25 0.  ]
 [0.   0.   0.   ... 0.19 0.25 0.  ]]


In [47]:
NDVI_2017_data[NDVI_2017_data == 0] = -999
NDVI_2018_data[NDVI_2018_data == 0] = -999

In [48]:
print(NDVI_2017_data)
print(NDVI_2018_data)

[[-9.99e+02 -9.99e+02 -9.99e+02 ... -9.99e+02  1.90e-01 -9.99e+02]
 [-9.99e+02 -9.99e+02 -9.99e+02 ... -9.99e+02 -9.99e+02 -9.99e+02]
 [ 6.00e-02 -9.99e+02 -9.99e+02 ... -9.99e+02 -9.99e+02 -9.99e+02]
 ...
 [-9.99e+02  6.00e-02  1.30e-01 ...  3.10e-01  2.50e-01 -9.99e+02]
 [-9.99e+02 -9.99e+02 -9.99e+02 ...  3.10e-01  3.10e-01 -9.99e+02]
 [-9.99e+02 -9.99e+02 -9.99e+02 ...  2.50e-01  3.10e-01 -9.99e+02]]
[[-9.99e+02 -9.99e+02 -9.99e+02 ... -9.99e+02 -9.99e+02 -9.99e+02]
 [ 6.00e-02 -9.99e+02 -9.99e+02 ... -9.99e+02 -9.99e+02 -9.99e+02]
 [ 1.30e-01 -9.99e+02 -9.99e+02 ... -9.99e+02 -9.99e+02 -9.99e+02]
 ...
 [-9.99e+02 -9.99e+02 -9.99e+02 ...  2.50e-01  3.10e-01 -9.99e+02]
 [-9.99e+02 -9.99e+02 -9.99e+02 ...  2.50e-01  2.50e-01 -9.99e+02]
 [-9.99e+02 -9.99e+02 -9.99e+02 ...  1.90e-01  2.50e-01 -9.99e+02]]


In [49]:
print(NDVI_2017.GetGeoTransform())
print(NDVI_2018.GetGeoTransform())
if NDVI_2017.GetGeoTransform()==NDVI_2018.GetGeoTransform(): print('Geotransformation OK')

(1936400.0, 40.0, 0.0, 5323880.0, 0.0, -40.0)
(1936400.0, 40.0, 0.0, 5323880.0, 0.0, -40.0)
Geotransformation OK


In [50]:
geotransform = NDVI_2017.GetGeoTransform()

originX,pixelWidth,empty,finalY,empty2,pixelHeight=geotransform
cols =  NDVI_2017.RasterXSize
rows =  NDVI_2017.RasterYSize

In [51]:
projection = NDVI_2017.GetProjection()

In [52]:
finalX = originX + pixelWidth * cols
originY = finalY + pixelHeight * rows

In [53]:
extentArray = [originX,finalX,originY,finalY]
def plotNDVI(ndviImage,extentArray,vmin,cmap):
    ndvi = gdal.Open(ndviImage)
    ds2019 = ndvi.ReadAsArray()
    plt.figure(figsize=(20,15))
    im = plt.imshow(ds2019, vmin=vmin, cmap=cmap, extent=extentArray)#
    plt.colorbar(im, fraction=0.015)
    plt.xlabel('Este')
    plt.ylabel('Norte')
    plt.show()

In [55]:
ndviChange = NDVI_2018_data-NDVI_2017_data
ndviChange = np.where((NDVI_2017_data>-999) & (NDVI_2018_data>-999),ndviChange,-999)
ndviChange

array([[-9.9900000e+02, -9.9900000e+02, -9.9900000e+02, ...,
        -9.9900000e+02, -9.9900000e+02, -9.9900000e+02],
       [-9.9900000e+02, -9.9900000e+02, -9.9900000e+02, ...,
        -9.9900000e+02, -9.9900000e+02, -9.9900000e+02],
       [ 6.9999993e-02, -9.9900000e+02, -9.9900000e+02, ...,
        -9.9900000e+02, -9.9900000e+02, -9.9900000e+02],
       ...,
       [-9.9900000e+02, -9.9900000e+02, -9.9900000e+02, ...,
        -6.0000002e-02,  6.0000002e-02, -9.9900000e+02],
       [-9.9900000e+02, -9.9900000e+02, -9.9900000e+02, ...,
        -6.0000002e-02, -6.0000002e-02, -9.9900000e+02],
       [-9.9900000e+02, -9.9900000e+02, -9.9900000e+02, ...,
        -6.0000002e-02, -6.0000002e-02, -9.9900000e+02]], dtype=float32)

In [56]:
def saveRaster(dataset,datasetPath,cols,rows,projection):
    rasterSet = gdal.GetDriverByName('GTiff').Create(datasetPath, cols, rows,1,gdal.GDT_Float32)
    rasterSet.SetProjection(projection)
    rasterSet.SetGeoTransform(geotransform)
    rasterSet.GetRasterBand(1).WriteArray(dataset)
    rasterSet.GetRasterBand(1).SetNoDataValue(-999)
    rasterSet = None

In [57]:
#Output NDVI Rasters 
path_NDVI_change = '../Output/NDVI_change.tif'

In [59]:
saveRaster(ndviChange,path_NDVI_change,cols,rows,projection)